### PR TITLE
added a paper

### PR DESCRIPTION
**Pull request by ChristopherMCollins**

### CODE REVIEW

**Comment by steveharoz** [comment]
Thanks Chris. Was there a revised submission? A "minor revision" decision is usually followed by revised submission (TVCG-XXX.R1) that gets an "accept" decision. One row has "minor" and the other row has "accept" for decisions.

**Comment by ChristopherMCollins** [comment]
Right, sorry. Will look that up and fix tomorrow.

Chris

**Comment by steveharoz** [comment]
ping

**Comment by ChristopherMCollins** [comment]
done

**Comment by steveharoz** [comment]
Thanks Chris!

**Pull request merged**
